### PR TITLE
feat: make Instructor the default branch and allow anyone to self-ass…

### PR DESCRIPTION
**Pull request by StoneyJackson**
…ign issues

* Instructor is now the default branch of GitKit.
* Anyone can claim an issue in the instance by commenting "I would like to work on this please!"

closes https://github.com/HFOSSedu/GitKit-Issues/issues/10
closes https://github.com/HFOSSedu/GitKit-Issues/issues/2

__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Review by braughtg — APPROVED** [review]
This looks good.  It worked for me!
- Seemed like I did not need the `git switch instructor` step since that is now the default.
- We'll need to be conscious of not allowing multiple assignments in Round2 where multiple people end up on the same issue.  Perhaps the activity just changes so that they don't claim it there?

**Comment by StoneyJackson** [comment]
@braughtg 

> * Seemed like I did not need the `git switch instructor` step since that is now the default.

Good point, I've removed that step from the README.

> * We'll need to be conscious of not allowing multiple assignments in Round2 where multiple people end up on the same issue.  Perhaps the activity just changes so that they don't claim it there?

Ah. So Round2 needs multiple people assigned to the same issue? Then yes, the action we're using does not support multiple self-assignment. Also, [private repositories under GitHub's free tier can only be assigned to a single user](https://docs.github.com/en/get-started/learning-about-github/faq-about-changes-to-githubs-plans#if-i-downgrade-from-github-team-or-a-legacy-plan-to-github-free-what-features-will-i-lose). So if multiple assignment is essential to the lesson, we should state that the instructor needs to deploy the kit into a public organization, or upgrade to a non-free plan in GitHub; and then we'd also need to augment the action to allow multiple self-assignment.

I'm going to merge this PR. If we need to make more changes, we can do that in a separate PR.

**Comment by StoneyJackson** [comment]
@braughtg Thanks for the review!

**Comment by braughtg** [comment]
> Ah. So Round2 needs multiple people assigned to the same issue? 

I think the thing to do is to take care of it in the learning activity, by not having them claim the second issue - or telling them to ignore the "Sorry" message.  Could be a good spot to talk about how some projects don't assign issues and other do.

**Comment by StoneyJackson** [comment]
@braughtg I need to review round 2 so I understand the situation better. My class should be starting git next week. So it's time I dug deeper anyway :)

**Pull request merged**
