### PR TITLE
1 create instance script

### PR DESCRIPTION
**Pull request by StoneyJackson**
__Pull Request Description__

* Closes https://github.com/HFOSSedu/GitKit-Issues/issues/1
* Closes https://github.com/HFOSSedu/GitKit-Issues/issues/9

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by StoneyJackson** [comment]
It's alive!

I need to write the docs, and the it's "done".

What's our review/merge procedure?

**Comment by StoneyJackson** [comment]
Ready for review.

If you choose to merge it, please use one of the squashing merge methods: "Squash and merge" or "Rebase and merge".

**Review by kwurst — CHANGES_REQUESTED** [review]
vscode ➜ /workspaces/cs101 (1-create-instance-script) $ .kit/bin/create_instance.py mytoken HFOSSedu/kwurst_kit
Fetched authenticated user kwurst
Traceback (most recent call last):
  File "/workspaces/cs101/.kit/bin/create_instance.py", line 16, in <module>
    repo_desc = github.RepoDescriptor(token, user, repo_name)
  File "/workspaces/cs101/.kit/pylib/kit/github/repo_descriptor.py", line 17, in __init__
    self.namespace = github.get_org(connection, parts[0])
  File "/workspaces/cs101/.kit/pylib/kit/github/get_org.py", line 5, in get_org
    org = connection.get_organization(org_name)
AttributeError: 'str' object has no attribute 'get_organization'

**Comment by StoneyJackson** [comment]
@kwurst I think I fixed that bug. Thanks for finding it!

**Review by kwurst — COMMENTED** [review]
@StoneyJackson 

Fix documentation:
.kit/README.md line 63 change `.kit/bin/create-instance.py` to `.kit/bin/create_instance.py`

New bug:

vscode ➜ /workspaces/gitkit (1-create-instance-script) $ .kit/bin/create_instance.py my_token HFOSSedu/kwurst-kit-review
Fetched authenticated user kwurst
Fetched organization HFOSSedu
Created empty repo https://api.github.com/repos/HFOSSedu/kwurst-kit-review
Deleted label bug
Deleted label documentation
Deleted label duplicate
Deleted label enhancement
Deleted label good first issue
Deleted label help wanted
Deleted label invalid
Deleted label question
Deleted label wontfix
Uploaded label: Round1
Uploaded label: Round2
Uploaded label: bug
Uploaded label: documentation
Uploaded label: duplicate
Uploaded label: enhancement
Uploaded label: good first issue
Uploaded label: help wanted
Uploaded label: invalid
Uploaded label: Links
Uploaded label: question
Uploaded label: Typos
Uploaded label: wontfix
Fetched label bug
Fetched label documentation
Fetched label duplicate
Fetched label enhancement
Fetched label good first issue
Fetched label help wanted
Fetched label invalid
Fetched label Links
Fetched label question
Fetched label Round1
Fetched label Round2
Fetched label Typos
Fetched label wontfix
Uploaded issue: Add Missing "a"
Uploaded issue: Format Role Names
Uploaded issue: Add Missing "with"
Uploaded issue: Fix Missing t Typo
Uploaded issue: Fix "comonent" Typo
Uploaded issue: Add Missing r To Fix Typo
Uploaded issue: Fix Missing t Typo
Uploaded issue: Fix Italics
Uploaded issue: Fix Typo of "ad" to "as"
Uploaded issue: Complete Truncated Sentence with Link
Uploaded issue: Add Missing "that"
Uploaded issue: Correct typo in "followign" 
Uploaded issue: Make it Plural
Uploaded issue: Make Starts Singular
Uploaded issue: Fix typo in "command"
Uploaded issue: Link for Setting Upstream Remote
Uploaded issue: Link for Pull Requests
Uploaded issue: Make "Fork" a link 
Uploaded issue: Comma Usage
Uploaded issue: Make Update plural
Uploaded issue: Change "is" to "it"
Uploaded issue: Remove duplicate "are"
Uploaded issue: Hyphenate step by step
Uploaded issue: Typo in Licensing Section
Uploaded issue: Remove mention of AUTHORS.md
Uploaded issue: Contributors "acknowledge" the DCO
Uploaded issue: Dickinson College Farm Link
Uploaded issue: NSF Award Link
Uploaded issue: GNOME CEC Link
Uploaded issue: Add farmOS Link
Traceback (most recent call last):
  File "/workspaces/gitkit/.kit/bin/create_instance.py", line 17, in <module>
    create_instance(token, user, repo_desc)
  File "/workspaces/gitkit/.kit/pylib/kit/create_instance.py", line 20, in create_instance
    remote = git.create_remote(local_repo, remote_name, authorizing_clone_url)
  File "/workspaces/gitkit/.kit/pylib/kit/git/create_remote.py", line 2, in create_remote
    local_repo.create_remote(remote_name, remote_url)
  File "/home/vscode/.local/lib/python3.10/site-packages/git/repo/base.py", line 458, in create_remote
    return Remote.create(self, name, url, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/git/remote.py", line 680, in create
    repo.git.remote(scmd, name, Git.polish_url(url), **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/git/cmd.py", line 638, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/git/cmd.py", line 1183, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/git/cmd.py", line 983, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(3)
  cmdline: git remote add kit_instance https://kwurst:*****@github.com/HFOSSedu/kwurst-kit-review.git
  stderr: 'error: remote kit_instance already exists.'

**Comment by kwurst** [comment]
@StoneyJackson 

Hold on. I think this is because I am reusing the same container.

Trying it again...

**Comment by kwurst** [comment]
@StoneyJackson 

OK. Bug fixed.

Only needs documentation fix:
.kit/README.md line 63 change `.kit/bin/create-instance.py` to `.kit/bin/create_instance.py`

**Comment by braughtg** [comment]
How critical is the 2.34 version on Git?  
* I had 2.21.1 by default
* I'm still on MacOS 10.14 and the update to 2.34 was a bear.
  * It took about two hours including all of the brew updates and other miscellaneous things.
  * I imagine newer MacOS versions will get it easily with the XCode CLI tools. ​But those are not compatable with older MacOS versions.

Installing docker, VSCode and the Remote Containers Extension were all simple.

I've got all the dependencies installed now.  I'll give the actual run a go tomorrow.

**Comment by StoneyJackson** [comment]
> How critical is the 2.34 version on Git?
> 
> * I had 2.21.1 by default
> * I'm still on MacOS 10.14 and the update to 2.34 was a bear.
>   
>   * It took about two hours including all of the brew updates and other miscellaneous things.
>   * I imagine newer MacOS versions will get it easily with the XCode CLI tools. ​But those are not compatable with older MacOS versions.
> 
> Installing docker, VSCode and the Remote Containers Extension were all simple.
> 
> I've got all the dependencies installed now. I'll give the actual run a go tomorrow.

2.34 is the version of git that I developed and tested against. The tool and the README instructions probable work with earlier git versions (v2.23 introduces `git switch` which I refer to in the instructions; could use `git checkout` instead - but there are [good reasons to use `git switch` instead](https://linuxhandbook.com/git-switch-checkout/) as general practice). 

The only real way to know is to try it with an older version and see if it works, and if it does, we can ratchet down the version numbers. So if you do, let me know which version it works for and I'll step it down.

**Comment by StoneyJackson** [comment]
> Only needs documentation fix: .kit/README.md line 63 change `.kit/bin/create-instance.py` to `.kit/bin/create_instance.py`

@kwurst Good catch. In fact create-instance.py was all over the pace. So I did a search and replace to create_instance.py. Thanks!

**Review by kwurst — APPROVED** [review]

**Comment by kwurst** [comment]
@StoneyJackson I did not see a squash option when I merged. What do we do now to fix that?

**Pull request merged**
